INSERT INTO Arena (ARENA_NAME, ADDRESS, CITY, ARENA_CAPACITY) VALUES ('Ullevi', 'Ullevigatan', 'Göteborg', 75000);

INSERT INTO CONCERT (ARTIST, DATE, TICKET_PRICE, ARENA_ID, CONCERT_DESCRIPTION, TICKETS_SOLD, PICTURE_ADDRESS) VALUES ('Aya Nakamura', '12/9', 900, 1, 'Aya Nakamura is a French-Malian pop singer.', 0, 'Hej');

