INSERT INTO Arena (ARENA_NAME, ADDRESS, CITY, ARENA_CAPACITY) VALUES ('Ullevi', 'Ullevigatan', 'Göteborg', 75000);
INSERT INTO Arena (ARENA_NAME, ADDRESS, CITY, ARENA_CAPACITY) VALUES ('Nalen', 'Regeringsgatan', 'Stockholm', 500);
INSERT INTO Arena (ARENA_NAME, ADDRESS, CITY, ARENA_CAPACITY) VALUES ('Globen', 'Arenavägen', 'Stockholm', 16000);
INSERT INTO Arena (ARENA_NAME, ADDRESS, CITY, ARENA_CAPACITY) VALUES ('Bern Arena', 'Restalundsvägen', 'Örebro', 12000);
INSERT INTO Arena (ARENA_NAME, ADDRESS, CITY, ARENA_CAPACITY) VALUES ('Malmö arena', 'Arenagatan', 'Malmö', 13000);
INSERT INTO Arena (ARENA_NAME, ADDRESS, CITY, ARENA_CAPACITY) VALUES ('Hovet', 'Arenaslingam', 'Stockholm', 8000);
INSERT INTO Arena (ARENA_NAME, ADDRESS, CITY, ARENA_CAPACITY) VALUES ('Berns', 'Berzelii park', 'Stockholm', 50);


INSERT INTO CONCERT (ARTIST, DATE, TICKET_PRICE, ARENA_ID, CONCERT_DESCRIPTION, TICKETS_SOLD, PICTURE_ADDRESS) VALUES ('Iron Maiden','12/8', 1099,(SELECT ID FROM ARENA WHERE ARENA_NAME= 'Ullevi'), 'Description', 0 ,'Bildadress');
INSERT INTO CONCERT (ARTIST, DATE, TICKET_PRICE, ARENA_ID, CONCERT_DESCRIPTION, TICKETS_SOLD, PICTURE_ADDRESS) VALUES ('Veronica Maggio','12/9', 699, (SELECT ID FROM ARENA WHERE ARENA_NAME= 'Nalen'), 'Description', 0 ,'Bildadress');
INSERT INTO CONCERT (ARTIST, DATE, TICKET_PRICE, ARENA_ID, CONCERT_DESCRIPTION, TICKETS_SOLD, PICTURE_ADDRESS) VALUES ('Zara Larsson','12/10', 899, (SELECT ID FROM ARENA WHERE ARENA_NAME= 'Globen'), 'Description', 0 ,'Bildadress');
INSERT INTO CONCERT (ARTIST, DATE, TICKET_PRICE, ARENA_ID, CONCERT_DESCRIPTION, TICKETS_SOLD, PICTURE_ADDRESS) VALUES ('Mustasch','12/11', 1459, (SELECT ID FROM ARENA WHERE ARENA_NAME= 'Bern Arena'), 'Description', 0 ,'Bildadress');
INSERT INTO CONCERT (ARTIST, DATE, TICKET_PRICE, ARENA_ID, CONCERT_DESCRIPTION, TICKETS_SOLD, PICTURE_ADDRESS) VALUES ('Timbuktu','12/12', 2992, (SELECT ID FROM ARENA WHERE ARENA_NAME = 'Berns'), 'Description', 0 ,'Bildadress');
INSERT INTO CONCERT (ARTIST, DATE, TICKET_PRICE, ARENA_ID, CONCERT_DESCRIPTION, TICKETS_SOLD, PICTURE_ADDRESS) VALUES ('Plura','1/8', 456, (SELECT ID FROM ARENA WHERE ARENA_NAME = 'Malmö arena'), 'Description', 0 ,'Bildadress');
INSERT INTO CONCERT (ARTIST, DATE, TICKET_PRICE, ARENA_ID, CONCERT_DESCRIPTION, TICKETS_SOLD, PICTURE_ADDRESS) VALUES ('Aya Nakamura','12/9', 900, (SELECT ID FROM ARENA WHERE ARENA_NAME = 'Hovet'), 'Description', 0 ,'Bildadress');
INSERT INTO CONCERT (ARTIST, DATE, TICKET_PRICE, ARENA_ID, CONCERT_DESCRIPTION, TICKETS_SOLD, PICTURE_ADDRESS) VALUES ('Ed Sheeran','3/10', 1300, (SELECT ID FROM ARENA WHERE ARENA_NAME = 'Berns'), 'Description', 0 ,'Bildadress');
INSERT INTO CONCERT (ARTIST, DATE, TICKET_PRICE, ARENA_ID, CONCERT_DESCRIPTION, TICKETS_SOLD, PICTURE_ADDRESS) VALUES ('Maleek Berry','6/7', 750, (SELECT ID FROM ARENA WHERE ARENA_NAME = 'Malmö arena'), 'Description', 0 ,'Bildadress');
INSERT INTO CONCERT (ARTIST, DATE, TICKET_PRICE, ARENA_ID, CONCERT_DESCRIPTION, TICKETS_SOLD, PICTURE_ADDRESS) VALUES ('Robyn','12/9', 900, (SELECT ID FROM ARENA WHERE ARENA_NAME = 'Hovet'), 'Description', 0 ,'Bildadress');
INSERT INTO CONCERT (ARTIST, DATE, TICKET_PRICE, ARENA_ID, CONCERT_DESCRIPTION, TICKETS_SOLD, PICTURE_ADDRESS) VALUES ('Lizzo','3/11', 900, (SELECT ID FROM ARENA WHERE ARENA_NAME = 'Berns'), 'Description', 0 ,'Bildadress');
INSERT INTO CONCERT (ARTIST, DATE, TICKET_PRICE, ARENA_ID, CONCERT_DESCRIPTION, TICKETS_SOLD, PICTURE_ADDRESS) VALUES ('Deorro','28/7', 750, (SELECT ID FROM ARENA WHERE ARENA_NAME = 'Malmö arena'), 'Description', 0 ,'Bildadress');

